#pragma once

// Made with <3 by me [Encryqed] && you [Fischsalat] + him [TempAccountNull]

// Mobile2Global
// 4.27.2-0+++UE4+Release-4.27

// Main-package: Engine
#include "pch.h"

#include <cmath>
#include <string>
#include <Windows.h>
#include <iostream>
#include <type_traits>

typedef __int8 int8;
typedef __int16 int16;
typedef __int32 int32;
typedef __int64 int64;

typedef unsigned __int8 uint8;
typedef unsigned __int16 uint16;
typedef unsigned __int32 uint32;
typedef unsigned __int64 uint64;

namespace Offsets {
	constexpr int32 GObjects = 0x03CDE9E0;
	constexpr int32 AppendString = 0x00AB9C80;
	constexpr int32 GNames = 0x00000000;
	constexpr int32 ProcessEvent = 0x00CB58A0;
	constexpr int32 ProcessEventIdx = 0x00000044;
}

#include "PropertyFixup.hpp"

#include "SDK/Basic.hpp"

#include "SDK/CoreUObject_structs.hpp"
#include "SDK/InputCore_structs.hpp"
#include "SDK/Chaos_structs.hpp"
#include "SDK/PhysicsCore_structs.hpp"
#include "SDK/AudioPlatformConfiguration_structs.hpp"
#include "SDK/SlateCore_structs.hpp"
#include "SDK/Slate_structs.hpp"
#include "SDK/PropertyAccess_structs.hpp"
#include "SDK/Engine_structs.hpp"
#include "SDK/MovieScene_structs.hpp"
#include "SDK/LevelSequence_structs.hpp"
#include "SDK/Qos_structs.hpp"
#include "SDK/metin2f_structs.hpp"
#include "SDK/trade_structs.hpp"
#include "SDK/PropertyPath_structs.hpp"
#include "SDK/MovieSceneTracks_structs.hpp"
#include "SDK/UMG_structs.hpp"
#include "SDK/MoviePlayer_structs.hpp"
#include "SDK/EyeTracker_structs.hpp"
#include "SDK/BlueprintFileUtils_structs.hpp"
#include "SDK/OnlineSubsystem_structs.hpp"
#include "SDK/OnlineSubsystemUtils_structs.hpp"
#include "SDK/stoneLight_structs.hpp"
#include "SDK/gorevBoxS_structs.hpp"
#include "SDK/MaterialShaderQualitySettings_structs.hpp"
#include "SDK/PacketHandler_structs.hpp"
#include "SDK/item_structs.hpp"
#include "SDK/PrivateShopView_structs.hpp"
#include "SDK/WebBrowserWidget_structs.hpp"
#include "SDK/Party_structs.hpp"
#include "SDK/banner_structs.hpp"
#include "SDK/AugmentedReality_structs.hpp"
#include "SDK/CinematicCamera_structs.hpp"
#include "SDK/ClothingSystemRuntimeInterface_structs.hpp"
#include "SDK/ClothingSystemRuntimeCommon_structs.hpp"
#include "SDK/Lobby_structs.hpp"
#include "SDK/fishOnay_structs.hpp"
#include "SDK/AudioMixer_structs.hpp"
#include "SDK/HeadMountedDisplay_structs.hpp"
#include "SDK/wsPanelMessage_structs.hpp"
#include "SDK/Hotfix_structs.hpp"
#include "SDK/ItemShopProduct_structs.hpp"
#include "SDK/Foliage_structs.hpp"
#include "SDK/Rejoin_structs.hpp"
#include "SDK/DeveloperSettings_structs.hpp"
#include "SDK/AutomationUtils_structs.hpp"
#include "SDK/quickSlot_structs.hpp"
#include "SDK/AnimatedTexture_structs.hpp"
#include "SDK/slot_structs.hpp"
#include "SDK/inventory_structs.hpp"
#include "SDK/Paper2D_structs.hpp"
#include "SDK/OodleNetworkHandlerComponent_structs.hpp"
#include "SDK/AndroidPermission_structs.hpp"
#include "SDK/MediaUtils_structs.hpp"
#include "SDK/MediaAssets_structs.hpp"
#include "SDK/PayBox_structs.hpp"
#include "SDK/AssetTags_structs.hpp"
#include "SDK/AudioExtensions_structs.hpp"
#include "SDK/w_view_structs.hpp"
#include "SDK/SoundFields_structs.hpp"
#include "SDK/JsonUtilities_structs.hpp"
#include "SDK/Synthesis_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/siralamaGuild_structs.hpp"
#include "SDK/AudioAnalyzer_structs.hpp"
#include "SDK/AudioSynesthesia_structs.hpp"
#include "SDK/Serialization_structs.hpp"
#include "SDK/EngineSettings_structs.hpp"
#include "SDK/charBox_structs.hpp"
#include "SDK/GameplayTags_structs.hpp"
#include "SDK/ImageWriteQueue_structs.hpp"
#include "SDK/MRMesh_structs.hpp"
#include "SDK/Wind_Update_Info_structs.hpp"
#include "SDK/friendBoxData_structs.hpp"
#include "SDK/dmDatas_structs.hpp"
#include "SDK/UI_structs.hpp"
#include "SDK/TimeManagement_structs.hpp"
#include "SDK/BuildPatchServices_structs.hpp"
#include "SDK/Landscape_structs.hpp"
#include "SDK/taskbar_structs.hpp"
#include "SDK/dialogue_structs.hpp"
#include "SDK/AnimationCore_structs.hpp"
#include "SDK/okeyGame_structs.hpp"
#include "SDK/AnimGraphRuntime_structs.hpp"
#include "SDK/ustDataObj_structs.hpp"
#include "SDK/NavigationSystem_structs.hpp"
#include "SDK/addPriv_structs.hpp"
#include "SDK/NetCore_structs.hpp"
#include "SDK/AssetRegistry_structs.hpp"
#include "SDK/c_Text_structs.hpp"
#include "SDK/MeshDescription_structs.hpp"
#include "SDK/StaticMeshDescription_structs.hpp"
#include "SDK/MovieSceneCapture_structs.hpp"
#include "SDK/Overlay_structs.hpp"
#include "SDK/mobAnim_structs.hpp"
#include "SDK/ClothingSystemRuntimeNv_structs.hpp"
#include "SDK/GameplayTasks_structs.hpp"
#include "SDK/c_TextBox_structs.hpp"
#include "SDK/AIModule_structs.hpp"
#include "SDK/EngineMessages_structs.hpp"
#include "SDK/zoomer_structs.hpp"
#include "SDK/ImageWrapper_structs.hpp"
#include "SDK/safeWall_structs.hpp"
#include "SDK/touchData_structs.hpp"
#include "SDK/cameraMove_structs.hpp"
#include "SDK/buttonType_structs.hpp"
#include "SDK/c_Button_structs.hpp"
#include "SDK/Renderer_structs.hpp"
#include "SDK/smsVerify_structs.hpp"
#include "SDK/SessionMessages_structs.hpp"
#include "SDK/WebBrowser_structs.hpp"
#include "SDK/DmgTypeBP_Environmental_structs.hpp"
#include "SDK/inventory_structs.hpp"
#include "SDK/m2data_structs.hpp"
#include "SDK/m2lib_structs.hpp"
#include "SDK/pControl_structs.hpp"
#include "SDK/skyBP_structs.hpp"
#include "SDK/m2save_structs.hpp"
#include "SDK/ItemShopBack_structs.hpp"
#include "SDK/dialogueButton_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/dmBox_structs.hpp"
#include "SDK/friendBox_structs.hpp"
#include "SDK/EscMenu_structs.hpp"
#include "SDK/Interface_Wind_Particle_True_structs.hpp"
#include "SDK/ItemShopPay_structs.hpp"
#include "SDK/w_window_structs.hpp"
#include "SDK/data_structs.hpp"
#include "SDK/loadingScreen_structs.hpp"
#include "SDK/splashScreen_structs.hpp"
#include "SDK/slotType_structs.hpp"
#include "SDK/slotStatus_structs.hpp"
#include "SDK/slot_structs.hpp"
#include "SDK/shopWindow_structs.hpp"
#include "SDK/chBox_structs.hpp"
#include "SDK/msgbox_structs.hpp"
#include "SDK/tasbas_structs.hpp"
#include "SDK/playerMenu_structs.hpp"
#include "SDK/okeyStart_structs.hpp"
#include "SDK/bar_structs.hpp"
#include "SDK/tip_structs.hpp"
#include "SDK/playerAnim_structs.hpp"
#include "SDK/Warrior_structs.hpp"
#include "SDK/TS_Fireworks_Shell_structs.hpp"
#include "SDK/drag1_structs.hpp"
#include "SDK/itemView_structs.hpp"
#include "SDK/eventBox_structs.hpp"
#include "SDK/costumeAttr_structs.hpp"
#include "SDK/roder_structs.hpp"
#include "SDK/goTargetEffect_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/addEvent_structs.hpp"
#include "SDK/NewGameStateBase_structs.hpp"
#include "SDK/privs_structs.hpp"
#include "SDK/newDm_structs.hpp"
#include "SDK/BP_Paticle_wind_settings_structs.hpp"
#include "SDK/BP_Particle_Snow_structs.hpp"
#include "SDK/wheather_structs.hpp"
#include "SDK/settings_structs.hpp"
#include "SDK/skills_structs.hpp"
#include "SDK/targetDetail_structs.hpp"
#include "SDK/UIhandler_structs.hpp"
#include "SDK/ustDatam_structs.hpp"
#include "SDK/ustData_structs.hpp"
#include "SDK/w_board_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/charSelect_structs.hpp"
#include "SDK/popup_structs.hpp"
#include "SDK/actorName_structs.hpp"
#include "SDK/catButton_structs.hpp"
#include "SDK/ItemShopBanner_structs.hpp"
#include "SDK/view_structs.hpp"
#include "SDK/focus_structs.hpp"
#include "SDK/ItemShopBuy_structs.hpp"
#include "SDK/pvpBox_structs.hpp"
#include "SDK/wsAsk_structs.hpp"
#include "SDK/playerWs_structs.hpp"
#include "SDK/yukItem_structs.hpp"
#include "SDK/ItemShopAddItem_structs.hpp"
#include "SDK/pop_item_structs.hpp"
#include "SDK/dmPlayerBox_structs.hpp"
#include "SDK/demirci_structs.hpp"
#include "SDK/joy_structs.hpp"
#include "SDK/mobileButton_structs.hpp"
#include "SDK/character_structs.hpp"
#include "SDK/Shaman2_structs.hpp"
#include "SDK/camZoom_structs.hpp"
#include "SDK/joyDrag_structs.hpp"
#include "SDK/askBox_structs.hpp"
#include "SDK/friendMenu_structs.hpp"
#include "SDK/loncaRutbe_structs.hpp"
#include "SDK/invButton_structs.hpp"
#include "SDK/groupMenu_structs.hpp"
#include "SDK/efsunbox_structs.hpp"
#include "SDK/dialogueText_structs.hpp"
#include "SDK/shopAdd_structs.hpp"
#include "SDK/chatboxMessage_structs.hpp"
#include "SDK/actorNameRPlayer_structs.hpp"
#include "SDK/actorNameMob_structs.hpp"
#include "SDK/TS_FireworksLauncher_structs.hpp"
#include "SDK/drag2_structs.hpp"
#include "SDK/particler_structs.hpp"
#include "SDK/chatBox_structs.hpp"
#include "SDK/community_structs.hpp"
#include "SDK/costume_structs.hpp"
#include "SDK/createShop_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/damge_structs.hpp"
#include "SDK/dmText_structs.hpp"
#include "SDK/efsunData_structs.hpp"
#include "SDK/empty_structs.hpp"
#include "SDK/events_structs.hpp"
#include "SDK/friendReqBox_structs.hpp"
#include "SDK/c2_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/friendRequest_structs.hpp"
#include "SDK/friendRequests_structs.hpp"
#include "SDK/loginScreen_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/loncaBox_structs.hpp"
#include "SDK/loncaUyeler_structs.hpp"
#include "SDK/makeLonca_structs.hpp"
#include "SDK/siralamaChar_structs.hpp"
#include "SDK/torch_structs.hpp"
#include "SDK/siralamaMetin_structs.hpp"
#include "SDK/siralamaMob_structs.hpp"
#include "SDK/wsPanel_structs.hpp"
#include "SDK/wsPanelUsageMessage_structs.hpp"
#include "SDK/okeyCard_structs.hpp"
#include "SDK/okeyCardDrag_structs.hpp"
#include "SDK/okeyCardView_structs.hpp"
#include "SDK/c_Border_structs.hpp"
#include "SDK/charBoxLonca_structs.hpp"
#include "SDK/mobileUI_structs.hpp"
#include "SDK/cursorW_structs.hpp"
#include "SDK/langButton_structs.hpp"
#include "SDK/msgboxLogin_structs.hpp"
#include "SDK/serverBox_structs.hpp"
#include "SDK/WebBrowser_structs.hpp"
#include "SDK/loncaRutbeChange_structs.hpp"
#include "SDK/ItemShop_structs.hpp"
#include "SDK/loading_structs.hpp"
#include "SDK/gorevBox_structs.hpp"
#include "SDK/gorevs_structs.hpp"
#include "SDK/group_structs.hpp"
#include "SDK/groupBox_structs.hpp"
#include "SDK/groupWant_structs.hpp"
#include "SDK/loncaWindow_structs.hpp"
#include "SDK/MallView_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/pop_ayir_structs.hpp"
#include "SDK/pop_equp_structs.hpp"
#include "SDK/reSpawn_structs.hpp"
#include "SDK/Warrior2_structs.hpp"
#include "SDK/Sura_structs.hpp"
#include "SDK/Sura2_structs.hpp"
#include "SDK/Ninja_structs.hpp"
#include "SDK/Ninja2_structs.hpp"
#include "SDK/Shaman_structs.hpp"
#include "SDK/campFire_structs.hpp"
#include "SDK/lamb_structs.hpp"
#include "SDK/mangal_structs.hpp"
#include "SDK/m2f_structs.hpp"
#include "SDK/w_viewSmall2_structs.hpp"
#include "SDK/dropInfo_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/mobAnim_Child_structs.hpp"
#include "SDK/CoreUObject_classes.hpp"
#include "SDK/PacketHandler_classes.hpp"
#include "SDK/DeveloperSettings_classes.hpp"
#include "SDK/PhysicsCore_classes.hpp"
#include "SDK/Engine_classes.hpp"
#include "SDK/MovieScene_classes.hpp"
#include "SDK/MovieSceneTracks_classes.hpp"
#include "SDK/UMG_classes.hpp"
#include "SDK/LevelSequence_classes.hpp"
#include "SDK/AudioMixer_classes.hpp"
#include "SDK/OnlineSubsystemUtils_classes.hpp"
#include "SDK/Qos_classes.hpp"
#include "SDK/trade_classes.hpp"
#include "SDK/MoviePlayer_classes.hpp"
#include "SDK/EyeTracker_classes.hpp"
#include "SDK/BlueprintFileUtils_classes.hpp"
#include "SDK/stoneLight_classes.hpp"
#include "SDK/gorevBoxS_classes.hpp"
#include "SDK/MaterialShaderQualitySettings_classes.hpp"
#include "SDK/PrivateShopView_classes.hpp"
#include "SDK/WebBrowserWidget_classes.hpp"
#include "SDK/Party_classes.hpp"
#include "SDK/metin2f_classes.hpp"
#include "SDK/banner_classes.hpp"
#include "SDK/AugmentedReality_classes.hpp"
#include "SDK/CinematicCamera_classes.hpp"
#include "SDK/ClothingSystemRuntimeInterface_classes.hpp"
#include "SDK/ClothingSystemRuntimeCommon_classes.hpp"
#include "SDK/Lobby_classes.hpp"
#include "SDK/fishOnay_classes.hpp"
#include "SDK/HeadMountedDisplay_classes.hpp"
#include "SDK/wsPanelMessage_classes.hpp"
#include "SDK/Hotfix_classes.hpp"
#include "SDK/ItemShopProduct_classes.hpp"
#include "SDK/Foliage_classes.hpp"
#include "SDK/Rejoin_classes.hpp"
#include "SDK/OnlineSubsystem_classes.hpp"
#include "SDK/AutomationUtils_classes.hpp"
#include "SDK/PropertyAccess_classes.hpp"
#include "SDK/quickSlot_classes.hpp"
#include "SDK/AnimatedTexture_classes.hpp"
#include "SDK/inventory_classes.hpp"
#include "SDK/Paper2D_classes.hpp"
#include "SDK/OodleNetworkHandlerComponent_classes.hpp"
#include "SDK/AndroidPermission_classes.hpp"
#include "SDK/MediaAssets_classes.hpp"
#include "SDK/PayBox_classes.hpp"
#include "SDK/AssetTags_classes.hpp"
#include "SDK/AudioExtensions_classes.hpp"
#include "SDK/w_view_classes.hpp"
#include "SDK/SoundFields_classes.hpp"
#include "SDK/JsonUtilities_classes.hpp"
#include "SDK/Synthesis_classes.hpp"
#include "SDK/mobAnim_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/siralamaGuild_classes.hpp"
#include "SDK/AudioAnalyzer_classes.hpp"
#include "SDK/AudioSynesthesia_classes.hpp"
#include "SDK/Serialization_classes.hpp"
#include "SDK/EngineSettings_classes.hpp"
#include "SDK/InputCore_classes.hpp"
#include "SDK/SlateCore_classes.hpp"
#include "SDK/charBox_classes.hpp"
#include "SDK/Slate_classes.hpp"
#include "SDK/GameplayTags_classes.hpp"
#include "SDK/ImageWriteQueue_classes.hpp"
#include "SDK/MRMesh_classes.hpp"
#include "SDK/Wind_Update_Info_classes.hpp"
#include "SDK/UI_classes.hpp"
#include "SDK/TimeManagement_classes.hpp"
#include "SDK/BuildPatchServices_classes.hpp"
#include "SDK/Landscape_classes.hpp"
#include "SDK/taskbar_classes.hpp"
#include "SDK/dialogue_classes.hpp"
#include "SDK/AnimationCore_classes.hpp"
#include "SDK/okeyGame_classes.hpp"
#include "SDK/AnimGraphRuntime_classes.hpp"
#include "SDK/ustDataObj_classes.hpp"
#include "SDK/NavigationSystem_classes.hpp"
#include "SDK/addPriv_classes.hpp"
#include "SDK/NetCore_classes.hpp"
#include "SDK/AssetRegistry_classes.hpp"
#include "SDK/c_Text_classes.hpp"
#include "SDK/MeshDescription_classes.hpp"
#include "SDK/StaticMeshDescription_classes.hpp"
#include "SDK/dmDatas_classes.hpp"
#include "SDK/MovieSceneCapture_classes.hpp"
#include "SDK/Overlay_classes.hpp"
#include "SDK/ClothingSystemRuntimeNv_classes.hpp"
#include "SDK/GameplayTasks_classes.hpp"
#include "SDK/c_TextBox_classes.hpp"
#include "SDK/AIModule_classes.hpp"
#include "SDK/EngineMessages_classes.hpp"
#include "SDK/zoomer_classes.hpp"
#include "SDK/ImageWrapper_classes.hpp"
#include "SDK/Chaos_classes.hpp"
#include "SDK/safeWall_classes.hpp"
#include "SDK/AudioPlatformConfiguration_classes.hpp"
#include "SDK/MediaUtils_classes.hpp"
#include "SDK/cameraMove_classes.hpp"
#include "SDK/c_Button_classes.hpp"
#include "SDK/Renderer_classes.hpp"
#include "SDK/smsVerify_classes.hpp"
#include "SDK/PropertyPath_classes.hpp"
#include "SDK/SessionMessages_classes.hpp"
#include "SDK/WebBrowser_classes.hpp"
#include "SDK/DmgTypeBP_Environmental_classes.hpp"
#include "SDK/m2data_classes.hpp"
#include "SDK/m2lib_classes.hpp"
#include "SDK/pControl_classes.hpp"
#include "SDK/skyBP_classes.hpp"
#include "SDK/m2save_classes.hpp"
#include "SDK/ItemShopBack_classes.hpp"
#include "SDK/dialogueButton_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/dmBox_classes.hpp"
#include "SDK/friendBox_classes.hpp"
#include "SDK/EscMenu_classes.hpp"
#include "SDK/Interface_Wind_Particle_True_classes.hpp"
#include "SDK/ItemShopPay_classes.hpp"
#include "SDK/w_window_classes.hpp"
#include "SDK/data_classes.hpp"
#include "SDK/loadingScreen_classes.hpp"
#include "SDK/splashScreen_classes.hpp"
#include "SDK/slot_classes.hpp"
#include "SDK/shopWindow_classes.hpp"
#include "SDK/chBox_classes.hpp"
#include "SDK/msgbox_classes.hpp"
#include "SDK/tasbas_classes.hpp"
#include "SDK/playerMenu_classes.hpp"
#include "SDK/okeyStart_classes.hpp"
#include "SDK/bar_classes.hpp"
#include "SDK/tip_classes.hpp"
#include "SDK/playerAnim_classes.hpp"
#include "SDK/Warrior_classes.hpp"
#include "SDK/TS_Fireworks_Shell_classes.hpp"
#include "SDK/drag1_classes.hpp"
#include "SDK/itemView_classes.hpp"
#include "SDK/slotStatus_classes.hpp"
#include "SDK/slotType_classes.hpp"
#include "SDK/eventBox_classes.hpp"
#include "SDK/costumeAttr_classes.hpp"
#include "SDK/roder_classes.hpp"
#include "SDK/goTargetEffect_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/addEvent_classes.hpp"
#include "SDK/NewGameStateBase_classes.hpp"
#include "SDK/privs_classes.hpp"
#include "SDK/newDm_classes.hpp"
#include "SDK/BP_Paticle_wind_settings_classes.hpp"
#include "SDK/BP_Particle_Snow_classes.hpp"
#include "SDK/wheather_classes.hpp"
#include "SDK/settings_classes.hpp"
#include "SDK/skills_classes.hpp"
#include "SDK/targetDetail_classes.hpp"
#include "SDK/UIhandler_classes.hpp"
#include "SDK/ustData_classes.hpp"
#include "SDK/w_board_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/ustDatam_classes.hpp"
#include "SDK/charSelect_classes.hpp"
#include "SDK/popup_classes.hpp"
#include "SDK/actorName_classes.hpp"
#include "SDK/catButton_classes.hpp"
#include "SDK/ItemShopBanner_classes.hpp"
#include "SDK/view_classes.hpp"
#include "SDK/focus_classes.hpp"
#include "SDK/ItemShopBuy_classes.hpp"
#include "SDK/pvpBox_classes.hpp"
#include "SDK/wsAsk_classes.hpp"
#include "SDK/playerWs_classes.hpp"
#include "SDK/yukItem_classes.hpp"
#include "SDK/ItemShopAddItem_classes.hpp"
#include "SDK/pop_item_classes.hpp"
#include "SDK/dmPlayerBox_classes.hpp"
#include "SDK/demirci_classes.hpp"
#include "SDK/joy_classes.hpp"
#include "SDK/mobileButton_classes.hpp"
#include "SDK/character_classes.hpp"
#include "SDK/Shaman2_classes.hpp"
#include "SDK/camZoom_classes.hpp"
#include "SDK/joyDrag_classes.hpp"
#include "SDK/askBox_classes.hpp"
#include "SDK/touchData_classes.hpp"
#include "SDK/friendMenu_classes.hpp"
#include "SDK/loncaRutbe_classes.hpp"
#include "SDK/invButton_classes.hpp"
#include "SDK/inventory_classes.hpp"
#include "SDK/slot_classes.hpp"
#include "SDK/groupMenu_classes.hpp"
#include "SDK/efsunbox_classes.hpp"
#include "SDK/dialogueText_classes.hpp"
#include "SDK/shopAdd_classes.hpp"
#include "SDK/chatboxMessage_classes.hpp"
#include "SDK/buttonType_classes.hpp"
#include "SDK/actorNameRPlayer_classes.hpp"
#include "SDK/actorNameMob_classes.hpp"
#include "SDK/TS_FireworksLauncher_classes.hpp"
#include "SDK/drag2_classes.hpp"
#include "SDK/particler_classes.hpp"
#include "SDK/chatBox_classes.hpp"
#include "SDK/community_classes.hpp"
#include "SDK/costume_classes.hpp"
#include "SDK/createShop_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/damge_classes.hpp"
#include "SDK/dmText_classes.hpp"
#include "SDK/efsunData_classes.hpp"
#include "SDK/empty_classes.hpp"
#include "SDK/events_classes.hpp"
#include "SDK/friendReqBox_classes.hpp"
#include "SDK/c2_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/friendRequest_classes.hpp"
#include "SDK/friendRequests_classes.hpp"
#include "SDK/loginScreen_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/loncaBox_classes.hpp"
#include "SDK/loncaUyeler_classes.hpp"
#include "SDK/makeLonca_classes.hpp"
#include "SDK/siralamaChar_classes.hpp"
#include "SDK/torch_classes.hpp"
#include "SDK/siralamaMetin_classes.hpp"
#include "SDK/siralamaMob_classes.hpp"
#include "SDK/wsPanel_classes.hpp"
#include "SDK/wsPanelUsageMessage_classes.hpp"
#include "SDK/okeyCard_classes.hpp"
#include "SDK/okeyCardDrag_classes.hpp"
#include "SDK/okeyCardView_classes.hpp"
#include "SDK/c_Border_classes.hpp"
#include "SDK/charBoxLonca_classes.hpp"
#include "SDK/mobileUI_classes.hpp"
#include "SDK/cursorW_classes.hpp"
#include "SDK/langButton_classes.hpp"
#include "SDK/msgboxLogin_classes.hpp"
#include "SDK/serverBox_classes.hpp"
#include "SDK/WebBrowser_classes.hpp"
#include "SDK/loncaRutbeChange_classes.hpp"
#include "SDK/ItemShop_classes.hpp"
#include "SDK/loading_classes.hpp"
#include "SDK/gorevBox_classes.hpp"
#include "SDK/gorevs_classes.hpp"
#include "SDK/group_classes.hpp"
#include "SDK/groupBox_classes.hpp"
#include "SDK/groupWant_classes.hpp"
#include "SDK/loncaWindow_classes.hpp"
#include "SDK/MallView_classes.hpp"
#include "SDK/friendBoxData_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/item_classes.hpp"
#include "SDK/pop_ayir_classes.hpp"
#include "SDK/pop_equp_classes.hpp"
#include "SDK/reSpawn_classes.hpp"
#include "SDK/Warrior2_classes.hpp"
#include "SDK/Sura_classes.hpp"
#include "SDK/Sura2_classes.hpp"
#include "SDK/Ninja_classes.hpp"
#include "SDK/Ninja2_classes.hpp"
#include "SDK/Shaman_classes.hpp"
#include "SDK/campFire_classes.hpp"
#include "SDK/lamb_classes.hpp"
#include "SDK/mangal_classes.hpp"
#include "SDK/m2f_classes.hpp"
#include "SDK/w_viewSmall2_classes.hpp"
#include "SDK/dropInfo_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/mobAnim_Child_classes.hpp"
#include "SDK/CoreUObject_parameters.hpp"
#include "SDK/InputCore_parameters.hpp"
#include "SDK/Chaos_parameters.hpp"
#include "SDK/DeveloperSettings_parameters.hpp"
#include "SDK/PhysicsCore_parameters.hpp"
#include "SDK/AudioPlatformConfiguration_parameters.hpp"
#include "SDK/PacketHandler_parameters.hpp"
#include "SDK/SlateCore_parameters.hpp"
#include "SDK/PropertyAccess_parameters.hpp"
#include "SDK/Slate_parameters.hpp"
#include "SDK/Engine_parameters.hpp"
#include "SDK/MovieScene_parameters.hpp"
#include "SDK/MovieSceneTracks_parameters.hpp"
#include "SDK/PropertyPath_parameters.hpp"
#include "SDK/UMG_parameters.hpp"
#include "SDK/LevelSequence_parameters.hpp"
#include "SDK/OnlineSubsystem_parameters.hpp"
#include "SDK/AudioMixer_parameters.hpp"
#include "SDK/OnlineSubsystemUtils_parameters.hpp"
#include "SDK/Qos_parameters.hpp"
#include "SDK/MoviePlayer_parameters.hpp"
#include "SDK/EyeTracker_parameters.hpp"
#include "SDK/metin2f_parameters.hpp"
#include "SDK/trade_parameters.hpp"
#include "SDK/BlueprintFileUtils_parameters.hpp"
#include "SDK/stoneLight_parameters.hpp"
#include "SDK/MaterialShaderQualitySettings_parameters.hpp"
#include "SDK/item_parameters.hpp"
#include "SDK/PrivateShopView_parameters.hpp"
#include "SDK/WebBrowserWidget_parameters.hpp"
#include "SDK/Party_parameters.hpp"
#include "SDK/banner_parameters.hpp"
#include "SDK/AugmentedReality_parameters.hpp"
#include "SDK/CinematicCamera_parameters.hpp"
#include "SDK/ClothingSystemRuntimeInterface_parameters.hpp"
#include "SDK/ClothingSystemRuntimeCommon_parameters.hpp"
#include "SDK/Lobby_parameters.hpp"
#include "SDK/fishOnay_parameters.hpp"
#include "SDK/HeadMountedDisplay_parameters.hpp"
#include "SDK/wsPanelMessage_parameters.hpp"
#include "SDK/Hotfix_parameters.hpp"
#include "SDK/ItemShopProduct_parameters.hpp"
#include "SDK/Foliage_parameters.hpp"
#include "SDK/Rejoin_parameters.hpp"
#include "SDK/AutomationUtils_parameters.hpp"
#include "SDK/AnimatedTexture_parameters.hpp"
#include "SDK/slot_parameters.hpp"
#include "SDK/inventory_parameters.hpp"
#include "SDK/Paper2D_parameters.hpp"
#include "SDK/OodleNetworkHandlerComponent_parameters.hpp"
#include "SDK/AndroidPermission_parameters.hpp"
#include "SDK/MediaUtils_parameters.hpp"
#include "SDK/MediaAssets_parameters.hpp"
#include "SDK/PayBox_parameters.hpp"
#include "SDK/AssetTags_parameters.hpp"
#include "SDK/AudioExtensions_parameters.hpp"
#include "SDK/w_view_parameters.hpp"
#include "SDK/SoundFields_parameters.hpp"
#include "SDK/JsonUtilities_parameters.hpp"
#include "SDK/Synthesis_parameters.hpp"
#include "SDK/AnimationCore_parameters.hpp"
#include "SDK/AnimGraphRuntime_parameters.hpp"
#include "SDK/mobAnim_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/siralamaGuild_parameters.hpp"
#include "SDK/AudioAnalyzer_parameters.hpp"
#include "SDK/AudioSynesthesia_parameters.hpp"
#include "SDK/Serialization_parameters.hpp"
#include "SDK/EngineSettings_parameters.hpp"
#include "SDK/charBox_parameters.hpp"
#include "SDK/GameplayTags_parameters.hpp"
#include "SDK/ImageWriteQueue_parameters.hpp"
#include "SDK/Wind_Update_Info_parameters.hpp"
#include "SDK/friendBoxData_parameters.hpp"
#include "SDK/dmDatas_parameters.hpp"
#include "SDK/quickSlot_parameters.hpp"
#include "SDK/UI_parameters.hpp"
#include "SDK/MRMesh_parameters.hpp"
#include "SDK/BuildPatchServices_parameters.hpp"
#include "SDK/TimeManagement_parameters.hpp"
#include "SDK/Landscape_parameters.hpp"
#include "SDK/taskbar_parameters.hpp"
#include "SDK/dialogue_parameters.hpp"
#include "SDK/okeyGame_parameters.hpp"
#include "SDK/ustDataObj_parameters.hpp"
#include "SDK/NavigationSystem_parameters.hpp"
#include "SDK/addPriv_parameters.hpp"
#include "SDK/NetCore_parameters.hpp"
#include "SDK/AssetRegistry_parameters.hpp"
#include "SDK/c_Text_parameters.hpp"
#include "SDK/MeshDescription_parameters.hpp"
#include "SDK/StaticMeshDescription_parameters.hpp"
#include "SDK/MovieSceneCapture_parameters.hpp"
#include "SDK/Overlay_parameters.hpp"
#include "SDK/ClothingSystemRuntimeNv_parameters.hpp"
#include "SDK/GameplayTasks_parameters.hpp"
#include "SDK/c_TextBox_parameters.hpp"
#include "SDK/AIModule_parameters.hpp"
#include "SDK/EngineMessages_parameters.hpp"
#include "SDK/zoomer_parameters.hpp"
#include "SDK/safeWall_parameters.hpp"
#include "SDK/touchData_parameters.hpp"
#include "SDK/cameraMove_parameters.hpp"
#include "SDK/buttonType_parameters.hpp"
#include "SDK/c_Button_parameters.hpp"
#include "SDK/smsVerify_parameters.hpp"
#include "SDK/SessionMessages_parameters.hpp"
#include "SDK/DmgTypeBP_Environmental_parameters.hpp"
#include "SDK/inventory_parameters.hpp"
#include "SDK/m2data_parameters.hpp"
#include "SDK/m2lib_parameters.hpp"
#include "SDK/pControl_parameters.hpp"
#include "SDK/skyBP_parameters.hpp"
#include "SDK/m2save_parameters.hpp"
#include "SDK/ItemShopBack_parameters.hpp"
#include "SDK/dialogueButton_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/dmBox_parameters.hpp"
#include "SDK/friendBox_parameters.hpp"
#include "SDK/EscMenu_parameters.hpp"
#include "SDK/Interface_Wind_Particle_True_parameters.hpp"
#include "SDK/ItemShopPay_parameters.hpp"
#include "SDK/w_window_parameters.hpp"
#include "SDK/data_parameters.hpp"
#include "SDK/loadingScreen_parameters.hpp"
#include "SDK/splashScreen_parameters.hpp"
#include "SDK/slotType_parameters.hpp"
#include "SDK/slotStatus_parameters.hpp"
#include "SDK/slot_parameters.hpp"
#include "SDK/shopWindow_parameters.hpp"
#include "SDK/chBox_parameters.hpp"
#include "SDK/msgbox_parameters.hpp"
#include "SDK/tasbas_parameters.hpp"
#include "SDK/playerMenu_parameters.hpp"
#include "SDK/okeyStart_parameters.hpp"
#include "SDK/bar_parameters.hpp"
#include "SDK/tip_parameters.hpp"
#include "SDK/playerAnim_parameters.hpp"
#include "SDK/Warrior_parameters.hpp"
#include "SDK/TS_Fireworks_Shell_parameters.hpp"
#include "SDK/drag1_parameters.hpp"
#include "SDK/itemView_parameters.hpp"
#include "SDK/eventBox_parameters.hpp"
#include "SDK/costumeAttr_parameters.hpp"
#include "SDK/roder_parameters.hpp"
#include "SDK/goTargetEffect_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/addEvent_parameters.hpp"
#include "SDK/NewGameStateBase_parameters.hpp"
#include "SDK/privs_parameters.hpp"
#include "SDK/newDm_parameters.hpp"
#include "SDK/BP_Paticle_wind_settings_parameters.hpp"
#include "SDK/BP_Particle_Snow_parameters.hpp"
#include "SDK/wheather_parameters.hpp"
#include "SDK/settings_parameters.hpp"
#include "SDK/skills_parameters.hpp"
#include "SDK/targetDetail_parameters.hpp"
#include "SDK/UIhandler_parameters.hpp"
#include "SDK/ustDatam_parameters.hpp"
#include "SDK/ustData_parameters.hpp"
#include "SDK/w_board_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/charSelect_parameters.hpp"
#include "SDK/popup_parameters.hpp"
#include "SDK/actorName_parameters.hpp"
#include "SDK/catButton_parameters.hpp"
#include "SDK/ItemShopBanner_parameters.hpp"
#include "SDK/view_parameters.hpp"
#include "SDK/focus_parameters.hpp"
#include "SDK/ItemShopBuy_parameters.hpp"
#include "SDK/pvpBox_parameters.hpp"
#include "SDK/wsAsk_parameters.hpp"
#include "SDK/playerWs_parameters.hpp"
#include "SDK/yukItem_parameters.hpp"
#include "SDK/ItemShopAddItem_parameters.hpp"
#include "SDK/dmPlayerBox_parameters.hpp"
#include "SDK/demirci_parameters.hpp"
#include "SDK/joy_parameters.hpp"
#include "SDK/mobileButton_parameters.hpp"
#include "SDK/character_parameters.hpp"
#include "SDK/Shaman2_parameters.hpp"
#include "SDK/camZoom_parameters.hpp"
#include "SDK/joyDrag_parameters.hpp"
#include "SDK/askBox_parameters.hpp"
#include "SDK/friendMenu_parameters.hpp"
#include "SDK/loncaRutbe_parameters.hpp"
#include "SDK/invButton_parameters.hpp"
#include "SDK/groupMenu_parameters.hpp"
#include "SDK/efsunbox_parameters.hpp"
#include "SDK/dialogueText_parameters.hpp"
#include "SDK/chatboxMessage_parameters.hpp"
#include "SDK/actorNameRPlayer_parameters.hpp"
#include "SDK/actorNameMob_parameters.hpp"
#include "SDK/TS_FireworksLauncher_parameters.hpp"
#include "SDK/drag2_parameters.hpp"
#include "SDK/particler_parameters.hpp"
#include "SDK/chatBox_parameters.hpp"
#include "SDK/community_parameters.hpp"
#include "SDK/costume_parameters.hpp"
#include "SDK/shopAdd_parameters.hpp"
#include "SDK/createShop_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/damge_parameters.hpp"
#include "SDK/dmText_parameters.hpp"
#include "SDK/efsunData_parameters.hpp"
#include "SDK/empty_parameters.hpp"
#include "SDK/events_parameters.hpp"
#include "SDK/friendReqBox_parameters.hpp"
#include "SDK/c2_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/friendRequest_parameters.hpp"
#include "SDK/friendRequests_parameters.hpp"
#include "SDK/loginScreen_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/loncaBox_parameters.hpp"
#include "SDK/loncaUyeler_parameters.hpp"
#include "SDK/makeLonca_parameters.hpp"
#include "SDK/siralamaChar_parameters.hpp"
#include "SDK/torch_parameters.hpp"
#include "SDK/siralamaMetin_parameters.hpp"
#include "SDK/siralamaMob_parameters.hpp"
#include "SDK/wsPanel_parameters.hpp"
#include "SDK/wsPanelUsageMessage_parameters.hpp"
#include "SDK/okeyCard_parameters.hpp"
#include "SDK/okeyCardDrag_parameters.hpp"
#include "SDK/okeyCardView_parameters.hpp"
#include "SDK/c_Border_parameters.hpp"
#include "SDK/charBoxLonca_parameters.hpp"
#include "SDK/mobileUI_parameters.hpp"
#include "SDK/cursorW_parameters.hpp"
#include "SDK/langButton_parameters.hpp"
#include "SDK/msgboxLogin_parameters.hpp"
#include "SDK/serverBox_parameters.hpp"
#include "SDK/WebBrowser_parameters.hpp"
#include "SDK/loncaRutbeChange_parameters.hpp"
#include "SDK/ItemShop_parameters.hpp"
#include "SDK/loading_parameters.hpp"
#include "SDK/gorevBox_parameters.hpp"
#include "SDK/gorevBoxS_parameters.hpp"
#include "SDK/gorevs_parameters.hpp"
#include "SDK/group_parameters.hpp"
#include "SDK/groupBox_parameters.hpp"
#include "SDK/groupWant_parameters.hpp"
#include "SDK/loncaWindow_parameters.hpp"
#include "SDK/MallView_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/pop_ayir_parameters.hpp"
#include "SDK/pop_item_parameters.hpp"
#include "SDK/pop_equp_parameters.hpp"
#include "SDK/reSpawn_parameters.hpp"
#include "SDK/Warrior2_parameters.hpp"
#include "SDK/Sura_parameters.hpp"
#include "SDK/Sura2_parameters.hpp"
#include "SDK/Ninja_parameters.hpp"
#include "SDK/Ninja2_parameters.hpp"
#include "SDK/Shaman_parameters.hpp"
#include "SDK/campFire_parameters.hpp"
#include "SDK/lamb_parameters.hpp"
#include "SDK/mangal_parameters.hpp"
#include "SDK/m2f_parameters.hpp"
#include "SDK/w_viewSmall2_parameters.hpp"
#include "SDK/dropInfo_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"
#include "SDK/mobAnim_Child_parameters.hpp"

static_assert(offsetof(SDK::UObject, Vft) == 0x0, "UObject::Vft has a wrong offset!");
static_assert(offsetof(SDK::UObject, Flags) == 0x8, "UObject::Flags has a wrong offset!");
static_assert(offsetof(SDK::UObject, Index) == 0xC, "UObject::Index has a wrong offset!");
static_assert(offsetof(SDK::UObject, Class) == 0x10, "UObject::Class has a wrong offset!");
static_assert(offsetof(SDK::UObject, Name) == 0x18, "UObject::Name has a wrong offset!");
static_assert(offsetof(SDK::UObject, Outer) == 0x20, "UObject::Outer has a wrong offset!");

static_assert(offsetof(SDK::FProperty, ElementSize) == 0x3C, "FProperty::ElementSize has a wrong offset!");
static_assert(offsetof(SDK::FProperty, PropertyFlags) == 0x40, "FProperty::PropertyFlags has a wrong offset!");
static_assert(offsetof(SDK::FProperty, Offset) == 0x4C, "FProperty::Offset has a wrong offset!");

static_assert(offsetof(SDK::UField, Next) == 0x30, "UField::Next has a wrong offset!");

static_assert(offsetof(SDK::FStructProperty, Struct) == 0x78, "FStructProperty::Struct has a wrong offset!");

static_assert(offsetof(SDK::UEnum, Names) == 0x48, "UEnum::Names has a wrong offset!");

static_assert(offsetof(SDK::UStruct, Super) == 0x48, "UStruct::Super has a wrong offset!");
static_assert(offsetof(SDK::UStruct, Children) == 0x50, "UStruct::Children has a wrong offset!");
static_assert(offsetof(SDK::UStruct, ChildProperties) == 0x58, "UStruct::ChildProperties has a wrong offset!");
static_assert(offsetof(SDK::UStruct, Size) == 0x60, "UStruct::Size has a wrong offset!");

static_assert(offsetof(SDK::UClass, CastFlags) == 0xD8, "UClass::CastFlags has a wrong offset!");
static_assert(offsetof(SDK::UClass, DefaultObject) == 0x120, "UClass::DefaultObject has a wrong offset!");

static_assert(offsetof(SDK::FMapProperty, KeyProperty) == 0x78, "FMapProperty::KeyProperty has a wrong offset!");
static_assert(offsetof(SDK::FMapProperty, ValueProperty) == 0x80, "FMapProperty::ValueProperty has a wrong offset!");

static_assert(offsetof(SDK::UFunction, FunctionFlags) == 0xB8, "UFunction::FunctionFlags has a wrong offset!");
static_assert(offsetof(SDK::UFunction, ExecFunction) == 0xE0, "UFunction::ExecFunction has a wrong offset!");

static_assert(offsetof(SDK::FClassProperty, MetaClass) == 0x80, "FClassProperty::MetaClass has a wrong offset!");

static_assert(offsetof(SDK::FByteProperty, Enum) == 0x78, "FByteProperty::Enum has a wrong offset!");

static_assert(offsetof(SDK::FFieldVariant, Container) == 0x0, "FFieldVariant::Container has a wrong offset!");
static_assert(offsetof(SDK::FFieldVariant, bIsUObject) == 0x8, "FFieldVariant::bIsUObject has a wrong offset!");
static_assert(offsetof(SDK::FFieldVariant, Pad) == 0x9, "FFieldVariant::Pad has a wrong offset!");

static_assert(offsetof(SDK::FBoolProperty, FieldSize) == 0x78, "FBoolProperty::FieldSize has a wrong offset!");
static_assert(offsetof(SDK::FBoolProperty, ByteOffset) == 0x79, "FBoolProperty::ByteOffset has a wrong offset!");
static_assert(offsetof(SDK::FBoolProperty, ByteMask) == 0x7A, "FBoolProperty::ByteMask has a wrong offset!");
static_assert(offsetof(SDK::FBoolProperty, FieldMask) == 0x7B, "FBoolProperty::FieldMask has a wrong offset!");

static_assert(offsetof(SDK::FObjectPropertyBase, PropertyClass) == 0x78, "FObjectPropertyBase::PropertyClass has a wrong offset!");

static_assert(offsetof(SDK::FArrayProperty, InnerProperty) == 0x78, "FArrayProperty::InnerProperty has a wrong offset!");

static_assert(offsetof(SDK::FSetProperty, ElementProperty) == 0x78, "FSetProperty::ElementProperty has a wrong offset!");

static_assert(offsetof(SDK::FEnumProperty, UnderlayingProperty) == 0x78, "FEnumProperty::UnderlayingProperty has a wrong offset!");
static_assert(offsetof(SDK::FEnumProperty, Enum) == 0x80, "FEnumProperty::Enum has a wrong offset!");

static_assert(offsetof(SDK::FFieldClass, Name) == 0x0, "FFieldClass::Name has a wrong offset!");
static_assert(offsetof(SDK::FFieldClass, Id) == 0x8, "FFieldClass::Id has a wrong offset!");
static_assert(offsetof(SDK::FFieldClass, CastFlags) == 0x10, "FFieldClass::CastFlags has a wrong offset!");
static_assert(offsetof(SDK::FFieldClass, ClassFlags) == 0x18, "FFieldClass::ClassFlags has a wrong offset!");
static_assert(offsetof(SDK::FFieldClass, SuperClass) == 0x20, "FFieldClass::SuperClass has a wrong offset!");

static_assert(offsetof(SDK::FField, Vft) == 0x0, "FField::Vft has a wrong offset!");
static_assert(offsetof(SDK::FField, Class) == 0x8, "FField::Class has a wrong offset!");
static_assert(offsetof(SDK::FField, Owner) == 0x10, "FField::Owner has a wrong offset!");
static_assert(offsetof(SDK::FField, Next) == 0x20, "FField::Next has a wrong offset!");
static_assert(offsetof(SDK::FField, Name) == 0x28, "FField::Name has a wrong offset!");
static_assert(offsetof(SDK::FField, Flags) == 0x30, "FField::Flags has a wrong offset!");